management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"

server:
  address: 192.168.1.104
  port: 18083

spring:
  rabbitmq:
    host: 192.168.1.132
    port: 15672
    username: guest
    password: guest
    virtual-host: /
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          search-paths: spring-cloud-config-repo
          uri: https://github.com/zdYng/spring-cloud-config-repo.git

eureka:
  client:
    serviceUrl:
      defaultZone: http://test:123456@192.168.1.104:8761/eureka
    instance:
      prefer-ip-address: true
