eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    instance-id: 192.168.1.104:8769
  client:
    service-url:
      defaultZone: http://test:123456@192.168.1.104:8761/eureka/

spring:
  application:
    name: service-zuul

server:
  address: 192.168.1.104
  port: 8769

zuul:
  routes:
    api-product:
      path: /api-product/**
      serviceId: product

    api-consumer:
      path: /api-consumer/**
      serviceId: consumer

    api-hhh:
      path: /api-hhh/**
      serviceId: hhh
    api-config:
      path: /api-config/**
      serviceId: config-client
management:
  security:
    enabled: false
